### ISSUE TITLE
Allow meshes to be dragged up and down

### ISSUE THREAD

**Issue by sarahriously** [PastaTime/DataRepVR#4]
Meshes get glitchy as hell when translating sometimes. 

Occasionally the mesh gets stuck at a really odd angle when translating and then remains at that odd angle.

A possible fix is using a 'control sphere' object at the edge of the mesh. We mirror the y coords to the mesh, but it's not a parent-child transform relationship.

**Comment by PastaTime** [comment]
b7ee7ed61796aa3c29938b469ddc5561c5d7f6e2
