### ISSUE TITLE
Cross-section tool

### ISSUE THREAD

**Issue by PastaTime** [PastaTime/DataRepVR#7]
The Cross Section tool should allow for a section of the mesh to be visualized

**Comment by sarahriously** [comment]
It all comes down to the shaders used. 
Current status of the cross-section tool is like this: ![2017-07-09 17_48_26-unity 5 6 1f1 personal 64bit - testing unity - datarepvr - pc mac linux sta](https://user-images.githubusercontent.com/13973759/27991555-c9776bd2-64ce-11e7-9a67-32a36dd04837.png)

The cross-section (cube for the time being) hides the meshes behind it. Ideally, it would hide the meshes in front of it and not obstruct the meshes behind it (the opposite of what we have now)

After some playing with shaders I was able to acheive this:
![2017-07-09 17_48_00-unity 5 6 1f1 personal 64bit - testing unity - datarepvr - pc mac linux sta](https://user-images.githubusercontent.com/13973759/27991565-fc312e78-64ce-11e7-88b4-a77659213536.png)
Where all objects (including the skybox) are blocked with the exception of the meshes, which are not obstructed at all.

**Comment by sarahriously** [comment]
If we cannot get the shaders working correctly we will either have to use the current shader (which renders the wrong way, back-to-front) or drop the feature entirely. It could be a lot of work to get the shaders behaving as desired, if it is even possible.
